spring:
  profiles:
    active: development
---
spring:
  profiles: cloud
  redis:
    host: 192.168.42.6
    port: 6379
  datasource:
    url: jdbc:mysql://192.168.42.2:3306/dev?useSSL=false
    username: root
    password: changsy2015
    initialize: false
    test-on-borrow: true
    connection-test-query: select 1
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: 127.0.0.1
      port: 8500
      config:
        enabled: true
        watch:
          enabled: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
---
spring:
  profiles: development
  redis:
    host: yuaoq.com
    port: 6379
  datasource:
    url: jdbc:mysql://192.168.99.100:9006/dev?useSSL=false
    username: root
    password: root
    initialize: false
    test-on-borrow: true
    connection-test-query: select 1
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: 127.0.0.1
      port: 8500
      config:
        enabled: true
        watch:
          enabled: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
---
spring:
  profiles: docker
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:mysql://mysql:3306/dev?useSSL=false
    username: root
    password: dbpass
    initialize: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DOCKER_IP:192.168.99.100}:8761/eureka/
---
spring:
  profiles: test
  redis:
    host: localhost
    port: 6379
  jpa:
    database: H2
  datasource:
    initialize: false
