spring:
  profiles:
    active: development
---
spring:
  profiles: cloud
  application:
      name: online-store-web
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        healthCheckUrl: http://localhost:${server.port}/health
      host: 127.0.0.1
      port: 8500
      config:
        enabled: true
        watch:
          enabled: true
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://localhost:9999
    auth-service:
      path: /user/**
      url: http://localhost:8181/uaa/user
    user-service:
      path: /users/**
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://yuaoq.com:8181/uaa/user
    client:
      accessTokenUri: http://yuaoq.com:8181/uaa/oauth/token
      userAuthorizationUri: http://yuaoq.com:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
  ignored: /assets/**,health
---
spring:
  profiles: development
  application:
    name: online-store-web
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: 127.0.0.1
      port: 8500
      config:
        enabled: true
        watch:
          enabled: true
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://localhost:9999
    auth-service:
      path: /user/**
      url: http://localhost:8181/uaa/user
    user-service:
      path: /users/**
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
    client:
      accessTokenUri: http://localhost:8181/uaa/oauth/token
      userAuthorizationUri: http://localhost:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
  ignored: /assets/**,health

---
spring:
  profiles: docker
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://${DOCKER_IP:192.168.99.100}:9999
    auth-service:
      path: /user/**
      url: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
    user-service:
      path: /users/**
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
    client:
      accessTokenUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/oauth/token
      userAuthorizationUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
    ip-address: 114.215.147.22
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DOCKER_IP:192.168.99.100}:8761/eureka/
