spring.profiles.active: development
---
spring:
  profiles: cloud
  data:
    mongodb:
      host: 192.168.42.5
      port: 27017
  mvc:
    date-format: "YYYY-MM-dd"
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: 127.0.0.1
      port: 8500
      config:
        enabled: true
        watch:
          enabled: true
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
    client:
      client-id: acme
      access-token-uri: http://localhost:8787
  ignored: /health
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
---
spring:
  profiles: development
  data:
    mongodb:
      host: yuaoq.com
      port: 27017
  mvc:
    date-format: "YYYY-MM-dd"
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: 127.0.0.1
      port: 8500
      config:
        enabled: true
        watch:
          enabled: true
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
    client:
      client-id: acme
      access-token-uri: http://localhost:8787
  ignored: /health
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
---
spring:
  profiles: docker
  data:
    mongodb:
      host: mongo
      port: 27017
  mvc:
    date-format: "YYYY-MM-dd"
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
security:
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
    client:
      client-id: acme
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 114.215.147.22
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DOCKER_IP:192.168.99.100}:8761/eureka/
