spring:
  profiles:
    active: development
---
server:
  port: 8181
  contextPath: /uaa
security:
  user:
    password: password
  enable-csrf: false
logging.level.org.springframework.security: DEBUG
spring:
  profiles: cloud
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        healthCheckUrl: http://localhost:8181/uaa/health
      host: 127.0.0.1
      port: 8500
      config:
        enabled: true
        watch:
          enabled: true
  datasource:
    url: jdbc:mysql://192.168.42.2:3306/dev?useSSL=false
    username: root
    password: changsy2015
    initialize: false
    test-on-borrow: true
    connection-test-query: select 1
security.ignored: /resources/**,/health
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 120000
---
server:
  port: 8181
  contextPath: /uaa
security:
  user:
    password: password
  enable-csrf: false
logging.level.org.springframework.security: DEBUG
spring:
  profiles: development
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        healthCheckUrl: http://localhost:8181/uaa/health
      host: 127.0.0.1
      port: 8500
      config:
        enabled: true
        watch:
          enabled: true
  datasource:
    url: jdbc:mysql://192.168.99.100:9006/dev?useSSL=false
    username: root
    password: root
    initialize: false
    test-on-borrow: true
    connection-test-query: select 1
security.ignored: /resources/**,/health
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 120000
---
server:
  port: 8181
  contextPath: /uaa
security:
  user:
    password: password
  enable-csrf: false
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql:3306/dev
    username: root
    password: dbpass
    initialize: true
security.ignored: /resources/**
eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: 8181
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false